{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tourmalinelabs.android",
    "module": "TLKit",
    "version": "23.2.25040300",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.getkeepsafe.relinker",
          "module": "relinker",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "TLKit-23.2.25040300.aar",
          "url": "TLKit-23.2.25040300.aar",
          "size": 12387293,
          "sha512": "87084111650797027370066d05ec2d5a670a0a25b9b82f8cb028552f9c62c0794a97587e93b76d244d2b4f4afe0b3e0ff9d4c598e0044e1bf991fc1ed3db0d45",
          "sha256": "d2e881c37e4fc4db0c26213372a7907f4e46b35b3629319090ea902f5601fcd5",
          "sha1": "cffd7aebb454e5257d3db1b8edb0de84f29c2a40",
          "md5": "866a96b430ace11c14e6cc89c81d4b12"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.getkeepsafe.relinker",
          "module": "relinker",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "TLKit-23.2.25040300.aar",
          "url": "TLKit-23.2.25040300.aar",
          "size": 12387293,
          "sha512": "87084111650797027370066d05ec2d5a670a0a25b9b82f8cb028552f9c62c0794a97587e93b76d244d2b4f4afe0b3e0ff9d4c598e0044e1bf991fc1ed3db0d45",
          "sha256": "d2e881c37e4fc4db0c26213372a7907f4e46b35b3629319090ea902f5601fcd5",
          "sha1": "cffd7aebb454e5257d3db1b8edb0de84f29c2a40",
          "md5": "866a96b430ace11c14e6cc89c81d4b12"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "TLKit-23.2.25040300-sources.jar",
          "url": "TLKit-23.2.25040300-sources.jar",
          "size": 588811,
          "sha512": "7237bdea4e98840fcd9b81447b9bbfb3af757c3a98a76d23cf064ad5b5f33a6014691f99ddf8e14aa712dc933c724514997f03a143ef9a8fd67eb978f3b8f2c2",
          "sha256": "e80195cd3ec321a56b5fe7d7ed744fcdc71b12238828a8c57591bf0a5238b4cb",
          "sha1": "f1275b0a45b53048fc89333971bfd9d2a975a912",
          "md5": "953d9af07952102ddd981744a82b48cf"
        }
      ]
    }
  ]
}
